/**
 * Entity definitions: table, columns, validation schema and search document per type.
 */
import type * as T from "../model/types";
import { schemas } from "../validation/schemas";
import type { EntityDef, ColKind } from "./repository";

const cols = (spec: Record<string, ColKind>) => spec;
const join = (...parts: (string | null | undefined)[]) => parts.filter(Boolean).join("\n");

export const semesterDef: EntityDef<T.Semester> = {
  type: "semester",
  table: "semesters",
  schema: schemas.semester,
  columns: cols({
    name: "text",
    academicYear: "text",
    type: "text",
    startDate: "text",
    endDate: "text",
    status: "text",
    isCurrent: "bool",
    gradingScaleId: "text",
    notes: "text",
  }),
  label: (e) => e.name,
  defaultOrder: "COALESCE(t.start_date, t.created_at) DESC",
};

export const gradingScaleDef: EntityDef<T.GradingScale> = {
  type: "grading_scale",
  table: "grading_scales",
  schema: schemas.gradingScale,
  columns: cols({ name: "text", kind: "text", maxPoints: "num", passMark: "num", bands: "json", isDefault: "bool" }),
  label: (e) => e.name,
  defaultOrder: "t.is_default DESC, t.name",
};

export const subjectDef: EntityDef<T.Subject> = {
  type: "subject",
  table: "subjects",
  schema: schemas.subject,
  hasTags: true,
  columns: cols({
    semesterId: "text",
    name: "text",
    code: "text",
    professor: "text",
    department: "text",
    credits: "num",
    classroom: "text",
    color: "text",
    description: "text",
    contactEmail: "text",
    contactPhone: "text",
    officeHours: "text",
    contactNotes: "text",
    links: "json",
    gradingScaleId: "text",
    targetGrade: "num",
    finalGradeOverride: "num",
    countsInGpa: "bool",
    attendanceThreshold: "num",
    folderRel: "text",
    status: "text",
    archived: "bool",
  }),
  label: (e) => e.name,
  search: (e) => ({
    title: join(e.name, e.code),
    body: join(e.professor, e.department, e.description, e.classroom, e.contactNotes),
    subjectId: e.id,
  }),
  defaultOrder: "t.name COLLATE NOCASE",
};

export const timetableDef: EntityDef<T.TimetableEntry> = {
  type: "timetable",
  table: "timetable_entries",
  schema: schemas.timetable,
  columns: cols({
    semesterId: "text",
    subjectId: "text",
    day: "num",
    startTime: "text",
    endTime: "text",
    kind: "text",
    room: "text",
    building: "text",
    professor: "text",
    color: "text",
    notes: "text",
    recurrence: "text",
    specificDate: "text",
    validFrom: "text",
    validUntil: "text",
  }),
  label: (e) => `${e.day} ${e.startTime}`,
  defaultOrder: "t.day, t.start_time",
};

export const lectureDef: EntityDef<T.Lecture> = {
  type: "lecture",
  table: "lectures",
  schema: schemas.lecture,
  columns: cols({
    subjectId: "text",
    number: "num",
    title: "text",
    date: "text",
    topic: "text",
    summary: "text",
    timetableEntryId: "text",
  }),
  label: (e) => e.title,
  search: (e) => ({ title: e.title, body: join(e.topic, e.summary), subjectId: e.subjectId, date: e.date }),
  defaultOrder: "COALESCE(t.date, '') DESC, t.number DESC",
};

export const attendanceDef: EntityDef<T.AttendanceRecord> = {
  type: "attendance",
  table: "attendance_records",
  schema: schemas.attendance,
  columns: cols({ subjectId: "text", lectureId: "text", timetableEntryId: "text", date: "text", status: "text", notes: "text" }),
  label: (e) => `${e.date} ${e.status}`,
  defaultOrder: "t.date DESC",
};

export const noteDef: EntityDef<T.Note> = {
  type: "note",
  table: "notes",
  schema: schemas.note,
  hasTags: true,
  columns: cols({
    title: "text",
    content: "text",
    contentText: "text",
    subjectId: "text",
    lectureId: "text",
    projectId: "text",
    noteType: "text",
    cyberTopic: "text",
    lectureDate: "text",
    status: "text",
    links: "json",
    pinned: "bool",
    favorite: "bool",
    archived: "bool",
    wordCount: "num",
    lastOpenedAt: "text",
  }),
  label: (e) => e.title,
  search: (e) => ({ title: e.title, body: e.contentText, subjectId: e.subjectId, date: e.lectureDate ?? e.updatedAt.slice(0, 10) }),
  defaultOrder: "t.pinned DESC, t.updated_at DESC",
};

export const fileDef: EntityDef<T.FileRecord> = {
  type: "file",
  table: "files",
  schema: schemas.file,
  hasTags: true,
  columns: cols({
    relPath: "text",
    name: "text",
    ext: "text",
    size: "num",
    sha256: "text",
    description: "text",
    subjectId: "text",
    projectId: "text",
    trashedAt: "text",
    trashRel: "text",
    lastOpenedAt: "text",
  }),
  label: (e) => e.name,
  search: (e) => (e.trashedAt ? null : { title: e.name, body: join(e.relPath, e.description), subjectId: e.subjectId }),
  defaultOrder: "t.name COLLATE NOCASE",
};

export const deadlineDef: EntityDef<T.Deadline> = {
  type: "deadline",
  table: "deadlines",
  schema: schemas.deadline,
  hasTags: true,
  columns: cols({
    title: "text",
    type: "text",
    subjectId: "text",
    projectId: "text",
    dueDate: "text",
    dueTime: "text",
    endTime: "text",
    location: "text",
    description: "text",
    priority: "text",
    status: "text",
    weight: "num",
    completedAt: "text",
  }),
  label: (e) => e.title,
  search: (e) => ({ title: e.title, body: join(e.description, e.location), subjectId: e.subjectId, date: e.dueDate }),
  defaultOrder: "t.due_date, COALESCE(t.due_time, '99:99')",
};

export const taskDef: EntityDef<T.Task> = {
  type: "task",
  table: "tasks",
  schema: schemas.task,
  hasTags: true,
  columns: cols({
    title: "text",
    description: "text",
    subjectId: "text",
    projectId: "text",
    deadlineId: "text",
    goalId: "text",
    milestoneId: "text",
    assigneeId: "text",
    dueDate: "text",
    dueTime: "text",
    priority: "text",
    status: "text",
    estimateMinutes: "num",
    actualMinutes: "num",
    notes: "text",
    recurrence: "json",
    recurrenceParentId: "text",
    rollover: "bool",
    completedAt: "text",
    sortOrder: "num",
  }),
  label: (e) => e.title,
  search: (e) => ({ title: e.title, body: join(e.description, e.notes), subjectId: e.subjectId, date: e.dueDate }),
  defaultOrder: "CASE WHEN t.due_date IS NULL THEN 1 ELSE 0 END, t.due_date, t.sort_order, t.created_at",
};

export const subtaskDef: EntityDef<T.Subtask> = {
  type: "subtask",
  table: "subtasks",
  schema: schemas.subtask,
  columns: cols({ taskId: "text", title: "text", done: "bool", sortOrder: "num" }),
  label: (e) => e.title,
  defaultOrder: "t.sort_order, t.created_at",
};

export const projectDef: EntityDef<T.Project> = {
  type: "project",
  table: "projects",
  schema: schemas.project,
  hasTags: true,
  columns: cols({
    name: "text",
    description: "text",
    subjectId: "text",
    semesterId: "text",
    professor: "text",
    startDate: "text",
    deadline: "text",
    priority: "text",
    status: "text",
    progress: "num",
    progressMode: "text",
    links: "json",
    color: "text",
    folderRel: "text",
  }),
  label: (e) => e.name,
  search: (e) => ({ title: e.name, body: join(e.description, e.professor), subjectId: e.subjectId, date: e.deadline }),
  defaultOrder: "CASE t.status WHEN 'archived' THEN 2 WHEN 'completed' THEN 1 ELSE 0 END, COALESCE(t.deadline, '9999'), t.name",
};

export const milestoneDef: EntityDef<T.Milestone> = {
  type: "milestone",
  table: "project_milestones",
  schema: schemas.milestone,
  columns: cols({
    projectId: "text",
    title: "text",
    description: "text",
    dueDate: "text",
    done: "bool",
    completedAt: "text",
    sortOrder: "num",
  }),
  label: (e) => e.title,
  defaultOrder: "COALESCE(t.due_date, '9999'), t.sort_order",
};

export const memberDef: EntityDef<T.ProjectMember> = {
  type: "member",
  table: "project_members",
  schema: schemas.member,
  columns: cols({
    projectId: "text",
    name: "text",
    role: "text",
    email: "text",
    phone: "text",
    contact: "text",
    responsibilities: "text",
    notes: "text",
    status: "text",
    isMe: "bool",
  }),
  label: (e) => e.name,
  defaultOrder: "t.is_me DESC, t.name COLLATE NOCASE",
};

export const meetingDef: EntityDef<T.Meeting> = {
  type: "meeting",
  table: "project_meetings",
  schema: schemas.meeting,
  columns: cols({
    projectId: "text",
    title: "text",
    date: "text",
    time: "text",
    location: "text",
    attendees: "json",
    agenda: "text",
    notes: "text",
    decisions: "text",
    actionItems: "json",
  }),
  label: (e) => e.title,
  search: (e) => ({
    title: e.title,
    body: join(e.agenda, e.notes, e.decisions, ...(e.actionItems ?? []).map((a) => a.text)),
    date: e.date,
  }),
  defaultOrder: "t.date DESC, t.time DESC",
};

export const gradeDef: EntityDef<T.GradeItem> = {
  type: "grade",
  table: "grade_items",
  schema: schemas.grade,
  columns: cols({
    subjectId: "text",
    name: "text",
    category: "text",
    weight: "num",
    score: "num",
    maxScore: "num",
    status: "text",
    date: "text",
    notes: "text",
    deadlineId: "text",
    sortOrder: "num",
  }),
  label: (e) => e.name,
  defaultOrder: "t.sort_order, t.created_at",
};

export const questionDef: EntityDef<T.Question> = {
  type: "question",
  table: "questions",
  schema: schemas.question,
  hasTags: true,
  columns: cols({
    text: "text",
    subjectId: "text",
    lectureId: "text",
    topic: "text",
    priority: "text",
    status: "text",
    answer: "text",
    noteId: "text",
    fileId: "text",
    answeredAt: "text",
  }),
  label: (e) => e.text,
  search: (e) => ({ title: e.text, body: join(e.topic, e.answer), subjectId: e.subjectId }),
  defaultOrder:
    "CASE t.status WHEN 'unresolved' THEN 0 WHEN 'researching' THEN 1 WHEN 'answered' THEN 2 ELSE 3 END, CASE t.priority WHEN 'urgent' THEN 0 WHEN 'high' THEN 1 WHEN 'medium' THEN 2 ELSE 3 END, t.created_at DESC",
};

export const journalDef: EntityDef<T.JournalEntry> = {
  type: "journal",
  table: "journal_entries",
  schema: schemas.journal,
  columns: cols({
    date: "text",
    mood: "num",
    energy: "num",
    studied: "text",
    completed: "text",
    learned: "text",
    notUnderstood: "text",
    problems: "text",
    tomorrow: "text",
    freeText: "text",
    subjectIds: "json",
    projectIds: "json",
  }),
  label: (e) => e.date,
  search: (e) => ({
    title: e.date,
    body: join(e.studied, e.completed, e.learned, e.notUnderstood, e.problems, e.tomorrow, e.freeText),
    date: e.date,
  }),
  defaultOrder: "t.date DESC",
};

export const resourceDef: EntityDef<T.ResearchResource> = {
  type: "resource",
  table: "research_resources",
  schema: schemas.resource,
  hasTags: true,
  columns: cols({
    title: "text",
    type: "text",
    authors: "text",
    subjectId: "text",
    projectId: "text",
    description: "text",
    fileId: "text",
    url: "text",
    readStatus: "text",
    favorite: "bool",
    notes: "text",
    citation: "text",
    year: "num",
    publisher: "text",
  }),
  label: (e) => e.title,
  search: (e) => ({
    title: e.title,
    body: join(e.authors, e.description, e.notes, e.citation, e.publisher, e.url),
    subjectId: e.subjectId,
  }),
  defaultOrder: "t.favorite DESC, t.created_at DESC",
};

export const goalDef: EntityDef<T.Goal> = {
  type: "goal",
  table: "goals",
  schema: schemas.goal,
  hasTags: true,
  columns: cols({
    title: "text",
    description: "text",
    semesterId: "text",
    deadline: "text",
    priority: "text",
    progress: "num",
    progressMode: "text",
    status: "text",
    category: "text",
    completedAt: "text",
  }),
  label: (e) => e.title,
  search: (e) => ({ title: e.title, body: join(e.description, e.category), date: e.deadline }),
  defaultOrder: "CASE t.status WHEN 'active' THEN 0 WHEN 'not_started' THEN 1 WHEN 'paused' THEN 2 ELSE 3 END, COALESCE(t.deadline, '9999')",
};

export const goalMilestoneDef: EntityDef<T.GoalMilestone> = {
  type: "goal_milestone",
  table: "goal_milestones",
  schema: schemas.goalMilestone,
  columns: cols({ goalId: "text", title: "text", done: "bool", dueDate: "text", sortOrder: "num" }),
  label: (e) => e.title,
  defaultOrder: "t.sort_order, t.created_at",
};

export const expenseDef: EntityDef<T.Expense> = {
  type: "expense",
  table: "expenses",
  schema: schemas.expense,
  columns: cols({
    amount: "num",
    currency: "text",
    category: "text",
    date: "text",
    description: "text",
    subjectId: "text",
    projectId: "text",
    semesterId: "text",
    paymentMethod: "text",
    receiptFileId: "text",
  }),
  label: (e) => `${e.amount} ${e.currency}`,
  search: (e) => (e.description ? { title: e.description, body: `${e.amount} ${e.currency}`, subjectId: e.subjectId, date: e.date } : null),
  defaultOrder: "t.date DESC, t.created_at DESC",
};

export const whiteboardDef: EntityDef<T.Whiteboard> = {
  type: "whiteboard",
  table: "whiteboards",
  schema: schemas.whiteboard,
  hasTags: true,
  columns: cols({ title: "text", fileRel: "text", subjectId: "text", projectId: "text", thumbnail: "text" }),
  label: (e) => e.title,
  search: (e) => ({ title: e.title, subjectId: e.subjectId }),
  defaultOrder: "t.updated_at DESC",
};

export const commandDef: EntityDef<T.CommandEntry> = {
  type: "command",
  table: "commands",
  schema: schemas.command,
  hasTags: true,
  columns: cols({
    title: "text",
    command: "text",
    tool: "text",
    category: "text",
    platform: "text",
    language: "text",
    explanation: "text",
    example: "text",
    expectedOutput: "text",
    warnings: "text",
    subjectId: "text",
    labId: "text",
    favorite: "bool",
  }),
  label: (e) => e.title || e.command,
  search: (e) => ({
    title: join(e.title, e.tool, e.command),
    body: join(e.explanation, e.example, e.expectedOutput, e.warnings),
    subjectId: e.subjectId,
  }),
  defaultOrder: "t.favorite DESC, t.tool COLLATE NOCASE, t.created_at DESC",
};

export const ctfDef: EntityDef<T.CtfChallenge> = {
  type: "ctf",
  table: "ctf_challenges",
  schema: schemas.ctf,
  hasTags: true,
  columns: cols({
    name: "text",
    platform: "text",
    event: "text",
    category: "text",
    difficulty: "text",
    url: "text",
    status: "text",
    points: "num",
    startedAt: "text",
    completedAt: "text",
    timeSpentMinutes: "num",
    tools: "json",
    hints: "text",
    solutionNotes: "text",
    writeup: "text",
    writeupText: "text",
    flag: "text",
  }),
  label: (e) => e.name,
  search: (e) => ({
    title: join(e.name, e.platform, e.event),
    body: join((e.tools ?? []).join(" "), e.hints, e.solutionNotes, e.writeupText),
    date: e.completedAt ?? e.startedAt,
  }),
  defaultOrder: "t.updated_at DESC",
};

export const labDef: EntityDef<T.CyberLab> = {
  type: "lab",
  table: "cyber_labs",
  schema: schemas.lab,
  hasTags: true,
  columns: cols({
    name: "text",
    objective: "text",
    environment: "text",
    tools: "json",
    steps: "text",
    findings: "text",
    errors: "text",
    lessons: "text",
    referencesText: "text",
    status: "text",
    subjectId: "text",
    startedAt: "text",
    completedAt: "text",
  }),
  label: (e) => e.name,
  search: (e) => ({
    title: e.name,
    body: join(e.objective, e.environment, (e.tools ?? []).join(" "), e.steps, e.findings, e.errors, e.lessons, e.referencesText),
    subjectId: e.subjectId,
    date: e.completedAt ?? e.startedAt,
  }),
  defaultOrder: "t.updated_at DESC",
};

export const roadmapDef: EntityDef<T.Roadmap> = {
  type: "roadmap",
  table: "roadmaps",
  schema: schemas.roadmap,
  columns: cols({ title: "text", track: "text", description: "text", color: "text" }),
  label: (e) => e.title,
  search: (e) => ({ title: e.title, body: e.description }),
  defaultOrder: "t.created_at",
};

export const roadmapItemDef: EntityDef<T.RoadmapItem> = {
  type: "roadmap_item",
  table: "roadmap_items",
  schema: schemas.roadmapItem,
  columns: cols({
    roadmapId: "text",
    title: "text",
    description: "text",
    status: "text",
    resourceUrl: "text",
    notes: "text",
    sortOrder: "num",
    completedAt: "text",
  }),
  label: (e) => e.title,
  search: (e) => ({ title: e.title, body: [e.description, e.notes].filter(Boolean).join("\n") }),
  defaultOrder: "t.sort_order, t.created_at",
};

export const studySessionDef: EntityDef<T.StudySession> = {
  type: "study_session",
  table: "study_sessions",
  schema: schemas.studySession,
  columns: cols({
    subjectId: "text",
    projectId: "text",
    taskId: "text",
    kind: "text",
    startedAt: "text",
    endedAt: "text",
    durationMinutes: "num",
    date: "text",
    notes: "text",
  }),
  label: (e) => `${e.date} ${e.durationMinutes}m`,
  defaultOrder: "t.started_at DESC",
};

export const ENTITY_DEFS = {
  semester: semesterDef,
  gradingScale: gradingScaleDef,
  subject: subjectDef,
  timetable: timetableDef,
  lecture: lectureDef,
  attendance: attendanceDef,
  note: noteDef,
  file: fileDef,
  deadline: deadlineDef,
  task: taskDef,
  subtask: subtaskDef,
  project: projectDef,
  milestone: milestoneDef,
  member: memberDef,
  meeting: meetingDef,
  grade: gradeDef,
  question: questionDef,
  journal: journalDef,
  resource: resourceDef,
  goal: goalDef,
  goalMilestone: goalMilestoneDef,
  expense: expenseDef,
  whiteboard: whiteboardDef,
  command: commandDef,
  ctf: ctfDef,
  lab: labDef,
  roadmap: roadmapDef,
  roadmapItem: roadmapItemDef,
  studySession: studySessionDef,
} as const;

export type EntityKey = keyof typeof ENTITY_DEFS;
