import {
  BookOpen,
  NotebookPen,
  File,
  AlarmClock,
  ListTodo,
  FolderKanban,
  CircleHelp,
  CalendarHeart,
  Library,
  Target,
  Wallet,
  PenTool,
  Terminal,
  Flag,
  FlaskConical,
  Route,
  Presentation,
  Users,
  CalendarRange,
  type LucideIcon,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  subject: BookOpen,
  note: NotebookPen,
  file: File,
  deadline: AlarmClock,
  task: ListTodo,
  project: FolderKanban,
  question: CircleHelp,
  journal: CalendarHeart,
  resource: Library,
  goal: Target,
  expense: Wallet,
  whiteboard: PenTool,
  command: Terminal,
  ctf: Flag,
  lab: FlaskConical,
  roadmap: Route,
  roadmap_item: Route,
  lecture: Presentation,
  meeting: Users,
  semester: CalendarRange,
};

export function entityIcon(type: string): LucideIcon {
  return ICONS[type] ?? File;
}

export const SEARCHABLE_TYPES = [
  "subject",
  "note",
  "file",
  "deadline",
  "task",
  "project",
  "meeting",
  "lecture",
  "question",
  "journal",
  "resource",
  "goal",
  "whiteboard",
  "command",
  "ctf",
  "lab",
  "roadmap",
  "roadmap_item",
  "expense",
] as const;
