/**
 * Notification center. Notifications are generated by scanning the data (lectures,
 * deadlines, tasks, goals, attendance, backups) and stored with a unique `dedupe_key`,
 * so each reminder is created exactly once no matter how often the scan runs.
 *
 * `title` stores an i18n key and `body` stores JSON params, so notifications are always
 * displayed in the current interface language.
 */
import type { AppNotification, Deadline } from "../model/types";
import type { NotificationCategory } from "../model/enums";
import type { Statement } from "../db/types";
import { combineDateTime, diffDays } from "../utils/dates";
import type { ServiceContext } from "./context";
import { nowIso, today } from "./context";
import { createTimetableService } from "./timetable";
import { attendanceStats } from "./subjects";

export interface NotificationPrefs {
  categories: Partial<Record<NotificationCategory, boolean>>;
  desktop: boolean;
  lectureLeadMinutes: number;
  backupReminderDays: number;
  lastBackupAt: string | null;
  goalWarningDays: number;
}

export const DEFAULT_NOTIFICATION_PREFS: NotificationPrefs = {
  categories: {},
  desktop: true,
  lectureLeadMinutes: 15,
  backupReminderDays: 7,
  lastBackupAt: null,
  goalWarningDays: 3,
};

export interface NotificationDraft {
  category: NotificationCategory;
  title: string;
  params: Record<string, string | number | null>;
  entityType: string | null;
  entityId: string | null;
  route: string | null;
  dedupeKey: string;
  triggerAt: string;
}

export interface NotificationFilter {
  status?: "unread" | "read" | "archived" | "active" | "all";
  category?: string | null;
  limit?: number;
}

function row(r: Record<string, unknown>): AppNotification {
  return {
    id: r.id as string,
    category: r.category as NotificationCategory,
    title: r.title as string,
    body: (r.body as string) ?? null,
    entityType: (r.entity_type as string) ?? null,
    entityId: (r.entity_id as string) ?? null,
    route: (r.route as string) ?? null,
    dedupeKey: r.dedupe_key as string,
    status: r.status as AppNotification["status"],
    snoozedUntil: (r.snoozed_until as string) ?? null,
    osDelivered: r.os_delivered === 1,
    triggerAt: r.trigger_at as string,
    createdAt: r.created_at as string,
    updatedAt: r.updated_at as string,
  };
}

function deadlineCategory(d: Deadline): NotificationCategory {
  if (d.type === "exam" || d.type === "quiz") return "exam";
  if (d.type === "project") return "project";
  return "assignment";
}

export function createNotificationService(ctx: ServiceContext) {
  const { repos } = ctx;
  const timetable = createTimetableService(ctx);

  const enabled = (prefs: NotificationPrefs, c: NotificationCategory) => prefs.categories[c] !== false;

  /** Computes the drafts that should exist at the current time (pure w.r.t. the database state). */
  async function collect(prefs: NotificationPrefs): Promise<NotificationDraft[]> {
    const now = ctx.clock.now();
    const nowMs = now.getTime();
    const t = today(ctx);
    const drafts: NotificationDraft[] = [];

    // 1. Upcoming lectures (today, within the lead time).
    if (enabled(prefs, "lecture")) {
      const current = await repos.semesters.list({ where: ["t.is_current = 1"], limit: 1 });
      const occ = await timetable.forDay(current[0]?.id ?? null, t);
      for (const o of occ) {
        const lead = prefs.lectureLeadMinutes * 60000;
        const startMs = o.start.getTime();
        if (nowMs >= startMs - lead && nowMs < startMs) {
          drafts.push({
            category: "lecture",
            title: "notif.lectureSoon",
            params: { subject: o.subject?.name ?? "", time: o.entry.startTime, room: o.entry.room ?? "" },
            entityType: "subject",
            entityId: o.entry.subjectId,
            route: `/subjects/${o.entry.subjectId}`,
            dedupeKey: `lecture:${o.entry.id}:${o.date}`,
            triggerAt: new Date(startMs - lead).toISOString(),
          });
        }
      }
    }

    // 2. Deadline reminders (exams, assignments, project deadlines…).
    const open = await repos.deadlines.list({ where: ["t.status NOT IN ('completed','submitted','cancelled')"] });
    if (open.length) {
      const rem = await ctx.db.query<{ entity_id: string; offset_minutes: number }>(
        "SELECT entity_id, offset_minutes FROM reminders WHERE entity_type = 'deadline'",
      );
      const offsets = new Map<string, number[]>();
      for (const r of rem) offsets.set(r.entity_id, [...(offsets.get(r.entity_id) ?? []), r.offset_minutes]);
      for (const d of open) {
        const cat = deadlineCategory(d);
        if (!enabled(prefs, cat)) continue;
        const due = combineDateTime(d.dueDate, d.dueTime);
        const dueMs = due.getTime();
        const stamp = `${d.dueDate}T${d.dueTime ?? "--"}`;
        if (nowMs >= dueMs) {
          drafts.push({
            category: cat,
            title: "notif.deadlineOverdue",
            params: { title: d.title, type: d.type, date: d.dueDate },
            entityType: "deadline",
            entityId: d.id,
            route: `/deadlines?open=${d.id}`,
            dedupeKey: `deadline-overdue:${d.id}:${stamp}`,
            triggerAt: due.toISOString(),
          });
          continue;
        }
        // Only the most recent reminder that is due now (avoids a burst when an item is created late).
        const passed = (offsets.get(d.id) ?? []).filter((o) => nowMs >= dueMs - o * 60000).sort((a, b) => a - b);
        if (passed.length) {
          const o = passed[0];
          drafts.push({
            category: cat,
            title: "notif.deadlineReminder",
            params: { title: d.title, type: d.type, days: diffDays(t, d.dueDate), time: d.dueTime ?? "" },
            entityType: "deadline",
            entityId: d.id,
            route: `/deadlines?open=${d.id}`,
            dedupeKey: `deadline:${d.id}:${o}:${stamp}`,
            triggerAt: new Date(dueMs - o * 60000).toISOString(),
          });
        }
      }
    }

    // 3. Project deadlines (7 days and 1 day before).
    if (enabled(prefs, "project")) {
      const projects = await repos.projects.list({ where: ["t.deadline IS NOT NULL", "t.status NOT IN ('completed','submitted','archived')"] });
      for (const p of projects) {
        const days = diffDays(t, p.deadline!);
        const bucket = days < 0 ? "overdue" : days <= 1 ? "1d" : days <= 7 ? "7d" : null;
        if (!bucket) continue;
        drafts.push({
          category: "project",
          title: days < 0 ? "notif.projectOverdue" : "notif.projectDeadline",
          params: { name: p.name, days },
          entityType: "project",
          entityId: p.id,
          route: `/projects/${p.id}`,
          dedupeKey: `project:${p.id}:${bucket}:${p.deadline}`,
          triggerAt: nowIso(ctx),
        });
      }
    }

    // 4. Tasks: one daily digest for overdue tasks and one for today's tasks.
    if (enabled(prefs, "task")) {
      const counts = await ctx.db.query<{ overdue: number; due_today: number }>(
        `SELECT SUM(CASE WHEN due_date < ? THEN 1 ELSE 0 END) AS overdue, SUM(CASE WHEN due_date = ? THEN 1 ELSE 0 END) AS due_today
         FROM tasks WHERE status NOT IN ('completed','cancelled')`,
        [t, t],
      );
      const c = counts[0];
      if (c?.overdue) {
        drafts.push({ category: "task", title: "notif.tasksOverdue", params: { count: c.overdue }, entityType: null, entityId: null, route: "/tasks?view=overdue", dedupeKey: `tasks-overdue:${t}`, triggerAt: nowIso(ctx) });
      }
      if (c?.due_today) {
        drafts.push({ category: "task", title: "notif.tasksToday", params: { count: c.due_today }, entityType: null, entityId: null, route: "/tasks?view=today", dedupeKey: `tasks-today:${t}`, triggerAt: nowIso(ctx) });
      }
    }

    // 5. Goals approaching their deadline without being finished.
    if (enabled(prefs, "goal")) {
      const goals = await repos.goals.list({ where: ["t.deadline IS NOT NULL", "t.status IN ('active','not_started')"] });
      for (const g of goals) {
        const days = diffDays(t, g.deadline!);
        if (days < 0 || days > prefs.goalWarningDays) continue;
        drafts.push({
          category: "goal",
          title: "notif.goalDeadline",
          params: { title: g.title, days },
          entityType: "goal",
          entityId: g.id,
          route: `/goals?open=${g.id}`,
          dedupeKey: `goal:${g.id}:${g.deadline}`,
          triggerAt: nowIso(ctx),
        });
      }
    }

    // 6. Attendance warnings (re-notifies only when the absence count changes).
    if (enabled(prefs, "attendance")) {
      const subjects = await repos.subjects.list({ where: ["t.archived = 0", "t.status = 'active'"] });
      if (subjects.length) {
        const recs = await repos.attendance.list({ where: [`t.subject_id IN (${subjects.map(() => "?").join(",")})`], params: subjects.map((s) => s.id) });
        for (const s of subjects) {
          const st = attendanceStats(recs.filter((r) => r.subjectId === s.id), s.attendanceThreshold);
          if (st.level !== "warning" && st.level !== "exceeded") continue;
          drafts.push({
            category: "attendance",
            title: st.level === "exceeded" ? "notif.attendanceExceeded" : "notif.attendanceWarning",
            params: { subject: s.name, percent: Math.round(st.absencePercent ?? 0), limit: s.attendanceThreshold },
            entityType: "subject",
            entityId: s.id,
            route: `/subjects/${s.id}/attendance`,
            dedupeKey: `attendance:${s.id}:${st.level}:${st.absent}`,
            triggerAt: nowIso(ctx),
          });
        }
      }
    }

    // 7. Backup reminder.
    if (enabled(prefs, "backup") && prefs.backupReminderDays > 0) {
      const last = prefs.lastBackupAt ? new Date(prefs.lastBackupAt).getTime() : 0;
      const ageDays = (nowMs - last) / 86400000;
      const hasData = ((await ctx.db.query<{ n: number }>("SELECT (SELECT COUNT(*) FROM subjects) + (SELECT COUNT(*) FROM notes) + (SELECT COUNT(*) FROM tasks) AS n"))[0]?.n ?? 0) > 0;
      if (hasData && ageDays >= prefs.backupReminderDays) {
        const windowKey = Math.floor(nowMs / (prefs.backupReminderDays * 86400000));
        drafts.push({
          category: "backup",
          title: last ? "notif.backupOld" : "notif.backupNever",
          params: { days: last ? Math.floor(ageDays) : null },
          entityType: null,
          entityId: null,
          route: "/backup",
          dedupeKey: `backup-reminder:${windowKey}`,
          triggerAt: nowIso(ctx),
        });
      }
    }
    return drafts;
  }

  function insertStatement(d: NotificationDraft): Statement {
    const now = nowIso(ctx);
    return {
      sql: `INSERT OR IGNORE INTO notifications (id, category, title, body, entity_type, entity_id, route, dedupe_key, status, os_delivered, trigger_at, created_at, updated_at)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, 'unread', 0, ?, ?, ?)`,
      params: [ctx.newId(), d.category, d.title, JSON.stringify(d.params), d.entityType, d.entityId, d.route, d.dedupeKey, d.triggerAt, now, now],
    };
  }

  const svc = {
    collect,

    /** Runs a scan and returns only the notifications created by this scan (never duplicates). */
    async scan(prefs: NotificationPrefs = DEFAULT_NOTIFICATION_PREFS): Promise<AppNotification[]> {
      const drafts = await collect(prefs);
      return svc.push(drafts);
    },

    /** Inserts drafts (e.g. workspace or missing-file problems raised by the app shell). */
    async push(drafts: NotificationDraft[]): Promise<AppNotification[]> {
      if (!drafts.length) return [];
      const changes = await ctx.db.batch(drafts.map(insertStatement));
      const createdKeys = drafts.filter((_, i) => changes[i] > 0).map((d) => d.dedupeKey);
      if (!createdKeys.length) return [];
      const rows = await ctx.db.query<Record<string, unknown>>(
        `SELECT * FROM notifications WHERE dedupe_key IN (${createdKeys.map(() => "?").join(",")})`,
        createdKeys,
      );
      return rows.map(row);
    },

    async list(f: NotificationFilter = {}): Promise<AppNotification[]> {
      const where: string[] = ["title <> '__deleted__'"];
      const params: (string | number)[] = [];
      const now = nowIso(ctx);
      const status = f.status ?? "active";
      if (status === "active") {
        where.push("status <> 'archived'", "(snoozed_until IS NULL OR snoozed_until <= ?)");
        params.push(now);
      } else if (status !== "all") {
        where.push("status = ?");
        params.push(status);
        if (status === "unread") {
          where.push("(snoozed_until IS NULL OR snoozed_until <= ?)");
          params.push(now);
        }
      }
      if (f.category) {
        where.push("category = ?");
        params.push(f.category);
      }
      params.push(f.limit ?? 300);
      const rows = await ctx.db.query<Record<string, unknown>>(
        `SELECT * FROM notifications ${where.length ? `WHERE ${where.join(" AND ")}` : ""} ORDER BY trigger_at DESC LIMIT ?`,
        params,
      );
      return rows.map(row);
    },

    async snoozed(): Promise<AppNotification[]> {
      const rows = await ctx.db.query<Record<string, unknown>>(
        "SELECT * FROM notifications WHERE status <> 'archived' AND snoozed_until > ? ORDER BY snoozed_until",
        [nowIso(ctx)],
      );
      return rows.map(row);
    },

    async unreadCount(): Promise<number> {
      const rows = await ctx.db.query<{ n: number }>(
        "SELECT COUNT(*) AS n FROM notifications WHERE status = 'unread' AND (snoozed_until IS NULL OR snoozed_until <= ?)",
        [nowIso(ctx)],
      );
      return rows[0]?.n ?? 0;
    },

    setStatus: (id: string, status: AppNotification["status"]) =>
      ctx.db.execute("UPDATE notifications SET status = ?, updated_at = ? WHERE id = ?", [status, nowIso(ctx), id]),
    markAllRead: () => ctx.db.execute("UPDATE notifications SET status = 'read', updated_at = ? WHERE status = 'unread'", [nowIso(ctx)]),
    snooze: (id: string, minutes: number) =>
      ctx.db.execute("UPDATE notifications SET snoozed_until = ?, status = 'unread', updated_at = ? WHERE id = ?", [
        new Date(ctx.clock.now().getTime() + minutes * 60000).toISOString(),
        nowIso(ctx),
        id,
      ]),
    /** Deleting keeps a tombstone (archived + hidden) so the same reminder is not generated again. */
    remove: (id: string) =>
      ctx.db.execute("UPDATE notifications SET status = 'archived', title = '__deleted__', body = NULL, updated_at = ? WHERE id = ?", [nowIso(ctx), id]),
    clearArchived: () => ctx.db.execute("UPDATE notifications SET title = '__deleted__', body = NULL WHERE status = 'archived'"),
    markOsDelivered: (id: string) => ctx.db.execute("UPDATE notifications SET os_delivered = 1 WHERE id = ?", [id]),

    /** Removes tombstones older than 180 days whose trigger has passed (cannot recur). */
    prune: () =>
      ctx.db.execute("DELETE FROM notifications WHERE status = 'archived' AND trigger_at < ?", [
        new Date(ctx.clock.now().getTime() - 180 * 86400000).toISOString(),
      ]),
  };
  return svc;
}
